os: linux
sudo: false
language: python

python:
- 2.7
- 3.5

install:
  - pip install tox

script:
  - tox

cache:
  - pip

branches:
  only:
    - master
    - /^.*-maintenance$/

notifications:
  email: false
