os: linux
sudo: false
language: python

matrix:
  include:
    - python: "2.6"
    - python: "2.7"
    - python: "3.2"
    - python: "3.3"
    - python: "3.4"
    - python: "3.5"
    - python: "nightly"
  allow_failures:
    - python: "2.6"
    - python: "3.2"
    - python: "nightly"

install:
  - pip install tox

script:
  - tox

cache:
  - pip

branches:
  only:
    - master
    - /^.*-maintenance$/

notifications:
  email: false
