os: linux
sudo: false
language: python

matrix:
  include:
    - python: 2.7
      env: TOXENV=py
    - python: 3.5
      env: TOXENV=py

install: pip install tox-travis
script: tox

cache:
  - pip

branches:
  only:
    - master
    - /^.*-maintenance$/

notifications:
  email: false
